language: node_js
node_js:
 - 10.16.3

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 6247db9a7c6efc7b7276ab3c98dc00dde2eb881f
 local_dir: dist
 on:
   branch: master