language: node_js
node_js:
 - 10.16.3

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 83d596da1b0a8671072ee73d5bd5c2b13f1233ca
 local_dir: dist
 on:
   branch: master